In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dtStores = pd.read_csv('dtStores.csv')
dtEmployees = pd.read_csv('dtEmployees.csv')
dtPayroll = pd.read_csv('dtPayroll.csv')
dtStoreActivity = pd.read_csv('dtStoreActivity.csv')

In [ ]:
dtEmployees.head(5)

,EmployeeID,StoreID,Department,EmploymentType,Gender,HourlyRate,ContractedWeeklyHours,HireYear,YearsTenure
0,EMP0001,STR001,Customer Service,FullTime,F,17.32,40,2023,1
1,EMP0002,STR001,Stocking,PartTime,F,19.48,20,2019,5
2,EMP0003,STR001,Cashier,FullTime,M,19.60,40,2017,7
3,EMP0004,STR001,Cashier,FullTime,M,20.53,40,2015,9
4,EMP0005,STR001,Stocking,PartTime,M,19.17,28,2017,7

In [ ]:
print('dtEmployees:', dtEmployees.shape)
print('dtPayroll:', dtPayroll.shape)
print('dtStores:', dtStores.shape)
print('dtStoreActivity:', dtStoreActivity.shape)

dtEmployees: (157, 9)
dtPayroll: (4082, 6)
dtStores: (15, 4)
dtStoreActivity: (780, 5)

In [ ]:
dtEmployees.isna().sum()

EmployeeID               0
StoreID                  0
Department               0
EmploymentType           0
Gender                   0
HourlyRate               0
ContractedWeeklyHours    0
HireYear                 0
YearsTenure              0
dtype: int64

In [ ]:
dtPayroll.isna().sum()

PayrollID            0
EmployeeID           0
StoreID              0
PayPeriod            0
ActualHoursWorked    0
GrossPayment         0
dtype: int64

In [ ]:
dtStoreActivity.isna().sum()

StoreID                      0
Week                         0
WeeklySales                  0
TransactionCount             0
CustomerSatisfactionScore    0
dtype: int64

In [ ]:
dtEmployees['Gender'].value_counts()

Gender
M    79
F    78
Name: count, dtype: int64

In [ ]:
dtEmployees['Department'].value_counts()

Department
Cashier             55
Stocking            42
Customer Service    32
Management          16
Security            12
Name: count, dtype: int64

In [ ]:
dtEmployees['EmploymentType'].value_counts()

EmploymentType
FullTime    100
PartTime     57
Name: count, dtype: int64

In [ ]:
dtEmployees['HourlyRate'].describe()

count    157.000000
mean      20.860828
std        5.426660
min       16.600000
25%       18.420000
50%       19.220000
75%       20.140000
max       40.840000
Name: HourlyRate, dtype: float64

In [ ]:
dtStores.head(10)

  StoreID     Region StoreSize  OpenedYear
0  STR001  Maritimes     Large        2011
1  STR002  Maritimes    Medium        2021
2  STR003    Alberta     Small        2011
3  STR004    Ontario    Medium        2019
4  STR005    Ontario     Large        2016
5  STR006     Quebec     Small        2014
6  STR007  Maritimes    Medium        2015
7  STR008    Alberta     Large        2018
8  STR009    Ontario     Small        2011
9  STR010    Alberta    Medium        2018

In [ ]:
dtEmployees.groupby('Department')['HourlyRate'].describe()

,count,mean,std,min,25%,50%,75%,max
Department,,,,,,,,
Cashier,55.0,19.108000,0.884244,17.61,18.4000,19.070,19.8300,20.61
Customer Service,32.0,18.580000,0.971666,17.20,17.6725,18.495,19.4675,20.13
Management,16.0,36.285625,3.615907,30.48,33.1650,36.970,39.7225,40.84
Security,12.0,19.083333,1.830779,16.60,17.9875,18.835,20.0575,22.49
Stocking,42.0,19.525714,0.917106,18.15,18.6325,19.455,20.0350,21.27

In [ ]:
dtEmployees.groupby('StoreID')['EmployeeID'].count().sort_values(ascending=False).head(5)

StoreID
STR001    18
STR005    18
STR008    18
STR013    18
STR004    10
Name: EmployeeID, dtype: int64

In [ ]:
dtPayroll['GrossPayment'].describe()

count    4082.000000
mean     1411.674929
std       560.798087
min       535.200000
25%      1035.180000
50%      1475.080000
75%      1601.600000
max      3384.360000
Name: GrossPayment, dtype: float64

In [ ]:
dtStoreActivity['WeeklySales'].describe()

count       780.000000
mean      45080.674538
std       27917.273410
min        9546.140000
25%       18117.180000
50%       40452.515000
75%       66856.270000
max      119130.490000
Name: WeeklySales, dtype: float64

In [ ]:
dtEmployees.sample(n=5, random_state=42)

,EmployeeID,StoreID,Department,EmploymentType,Gender,HourlyRate,ContractedWeeklyHours,HireYear,YearsTenure
126,EMP0127,STR013,Stocking,FullTime,F,21.17,40,2019,5
45,EMP0046,STR005,Management,FullTime,M,36.20,40,2018,6
133,EMP0134,STR013,Cashier,FullTime,M,19.23,40,2015,9
138,EMP0139,STR013,Cashier,PartTime,F,19.57,20,2019,5
111,EMP0112,STR011,Cashier,FullTime,M,17.94,40,2023,1

In [ ]:
dtEmployees.groupby('Gender')['HourlyRate'].mean()

Gender
F    20.361026
M    21.354304
Name: HourlyRate, dtype: float64

In [ ]:
dtEmployees.groupby(['Department','EmploymentType'])['EmployeeID'].count()

Department        EmploymentType
Cashier           FullTime          34
                  PartTime          21
Customer Service  FullTime          21
                  PartTime          11
Management        FullTime          11
                  PartTime           5
Security          FullTime           9
                  PartTime           3
Stocking          FullTime          25
                  PartTime          17
Name: EmployeeID, dtype: int64

In [ ]:
dtStores['StoreSize'].value_counts()

StoreSize
Medium    6
Small     5
Large     4
Name: count, dtype: int64

In [ ]:
dtEmployees.groupby('HireYear')['EmployeeID'].count().sort_index()

HireYear
2015    11
2016    14
2017    25
2018    12
2019    26
2020    19
2021    19
2022    12
2023    19
Name: EmployeeID, dtype: int64

## Analysis

In [ ]:
pay_by_dept_gender = dtEmployees.groupby(['Department', 'Gender']).agg(
    avgHourlyRate=('HourlyRate', 'mean'),
    employeeCount=('EmployeeID', 'count')
).unstack()
pay_by_dept_gender

                 avgHourlyRate            employeeCount
Gender                       F          M             F   M
Department
Cashier              19.378500  18.953429            20  35
Customer Service     18.632353  18.520667            17  15
Management           32.640000  39.121111             7   9
Security             18.037500  21.175000             8   4
Stocking             19.656154  19.313750            26  16

In [ ]:
pay_gap = dtEmployees.groupby(['Department', 'Gender'])['HourlyRate'].mean().unstack()
pay_gap['payGapPct'] = (
    (pay_gap['M'] - pay_gap['F']) / pay_gap['M'] * 100
).round(2)
pay_gap

Gender                    F          M  payGapPct
Department
Cashier           19.378500  18.953429      -2.24
Customer Service  18.632353  18.520667      -0.60
Management        32.640000  39.121111      16.57
Security          18.037500  21.175000      14.82
Stocking          19.656154  19.313750      -1.77

In [ ]:
threshold = 5.0
flagged_depts = pay_gap.loc[pay_gap['payGapPct'] > threshold].copy()
print(f'Departments with pay gap exceeding {threshold}% threshold:')
display(flagged_depts)
print(f'\nNumber of departments breaching threshold: {len(flagged_depts)}')

Departments with pay gap exceeding 5.0% threshold:

Gender            F          M  payGapPct
Department
Management  32.6400  39.121111      16.57
Security    18.0375  21.175000      14.82

Number of departments breaching threshold: 2

In [ ]:
dtEmployees.groupby('Department')['YearsTenure'].mean().sort_values(ascending=False)

Department
Stocking            5.500000
Cashier             4.818182
Management          4.687500
Security            4.416667
Customer Service    4.375000
Name: YearsTenure, dtype: float64

In [ ]:
dtEmployees.groupby(['StoreID','Gender'])['EmployeeID'].count().head(10)

StoreID  Gender
STR001   F         10
         M          8
STR002   F          3
         M          7
STR003   F          3
         M          2
STR004   F          7
         M          3
STR005   F          4
         M         14
Name: EmployeeID, dtype: int64

In [ ]:
dtEmployees.merge(dtStores[['StoreID','Region']], on='StoreID').groupby('Region')['HourlyRate'].mean()

Region
Alberta      23.075417
BC           20.285000
Maritimes    19.578491
Ontario      19.521818
Quebec       24.104000
Name: HourlyRate, dtype: float64

In [ ]:
dtEmployees.loc[dtEmployees['Department'] == 'Management'].sort_values('HourlyRate', ascending=False).head(10)

,EmployeeID,StoreID,Department,EmploymentType,Gender,HourlyRate,ContractedWeeklyHours,HireYear,YearsTenure
24,EMP0025,STR002,Management,PartTime,M,40.84,28,2016,8
103,EMP0104,STR010,Management,FullTime,M,40.29,40,2020,4
141,EMP0142,STR013,Management,FullTime,M,40.24,40,2015,9
152,EMP0153,STR015,Management,FullTime,M,40.12,40,2022,2
62,EMP0063,STR006,Management,FullTime,M,39.59,40,2021,3
150,EMP0151,STR015,Management,FullTime,M,38.94,40,2015,9
144,EMP0145,STR014,Management,FullTime,M,38.13,40,2019,5
148,EMP0149,STR015,Management,FullTime,M,37.74,40,2023,1
45,EMP0046,STR005,Management,FullTime,M,36.20,40,2018,6
145,EMP0146,STR014,Management,PartTime,F,34.43,20,2022,2

In [ ]:
affected = dtEmployees.loc[
    (dtEmployees['Department'].isin(flagged_depts.index)) &
    (dtEmployees['Gender'] == 'F')
]
print(f'Female employees in flagged departments: {len(affected)}')

male_avg = dtEmployees.loc[
    dtEmployees['Department'].isin(flagged_depts.index) &
    (dtEmployees['Gender'] == 'M')
].groupby('Department')['HourlyRate'].mean()

affected = affected.merge(male_avg.rename('maleAvgRate'), on='Department', how='left')
affected['annualPayGap'] = (
    (affected['maleAvgRate'] - affected['HourlyRate']) *
    affected['ContractedWeeklyHours'] * 52
)
total_gap = affected['annualPayGap'].sum()
print(f'Total annual pay gap exposure: ${total_gap:,.2f}')

Female employees in flagged departments: 15
Total annual pay gap exposure: $114,462.52

In [ ]:
display(affected)

,EmployeeID,StoreID,Department,EmploymentType,Gender,HourlyRate,ContractedWeeklyHours,HireYear,YearsTenure,maleAvgRate,annualPayGap
0,EMP0031,STR003,Management,FullTime,F,32.73,40,2023,1,39.121111,13293.511111
1,EMP0035,STR004,Security,FullTime,F,19.09,40,2019,5,21.175000,4336.800000
2,EMP0073,STR007,Management,PartTime,F,31.17,28,2017,7,39.121111,11576.817778
3,EMP0074,STR007,Security,PartTime,F,17.77,28,2022,2,21.175000,4957.680000
4,EMP0077,STR008,Management,FullTime,F,30.48,40,2016,8,39.121111,17973.511111
5,EMP0080,STR008,Security,PartTime,F,18.23,16,2020,4,21.175000,2450.240000
6,EMP0087,STR008,Management,PartTime,F,33.31,16,2023,1,39.121111,4834.844444
7,EMP0091,STR008,Management,PartTime,F,34.02,16,2020,4,39.121111,4244.124444
8,EMP0093,STR008,Security,PartTime,F,18.89,16,2017,7,21.175000,1901.120000
9,EMP0110,STR011,Security,FullTime,F,16.88,40,2019,5,21.175000,8933.600000
10,EMP0121,STR012,Security,FullTime,F,18.78,40,2019,5,21.175000,4981.600000
11,EMP0138,STR013,Security,FullTime,F,16.60,40,2016,8,21.175000,9516.000000
12,EMP0146,STR014,Management,PartTime,F,34.43,20,2022,2,39.121111,4878.755556
13,EMP0147,STR014,Security,FullTime,F,18.06,40,2023,1,21.175000,6479.200000
14,EMP0150,STR015,Management,FullTime,F,32.34,40,2019,5,39.121111,14104.711111

In [ ]:
dtStoreActivity.groupby('StoreID')['CustomerSatisfactionScore'].mean().sort_values(ascending=False).head(5)

StoreID
STR011    4.108846
STR013    4.075385
STR003    4.060577
STR002    4.027308
STR004    4.022692
Name: CustomerSatisfactionScore, dtype: float64

In [ ]:
dtStoreActivity.groupby('Week')['WeeklySales'].sum().head(10)

Week
1     696866.48
2     707668.61
3     730800.24
4     724549.15
5     734859.09
6     724274.42
7     768365.62
8     777748.47
9     757718.08
10    774409.97
Name: WeeklySales, dtype: float64

In [ ]:
dtPayroll.merge(dtEmployees[['EmployeeID','Department']], on='EmployeeID').groupby('Department')['GrossPayment'].sum().sort_values(ascending=False)

Department
Cashier             1848389.24
Stocking            1397095.90
Customer Service    1048309.42
Management          1047759.74
Security             420902.76
Name: GrossPayment, dtype: float64

In [ ]:
dtPayroll.merge(dtEmployees[['EmployeeID','EmploymentType']], on='EmployeeID').groupby('EmploymentType')['GrossPayment'].sum()

EmploymentType
FullTime    4416729.00
PartTime    1345728.06
Name: GrossPayment, dtype: float64

In [ ]:
pd.crosstab(dtEmployees['Department'], dtEmployees['Gender'], normalize='index').round(2)

Gender               F     M
Department
Cashier           0.36  0.64
Customer Service  0.53  0.47
Management        0.44  0.56
Security          0.67  0.33
Stocking          0.62  0.38

In [ ]:
pd.crosstab(dtStores['Region'], dtStores['StoreSize'])

StoreSize  Large  Medium  Small
Region
Alberta        1       2      2
BC             1       0      0
Maritimes      1       3      1
Ontario        1       1      1
Quebec         0       0      1

In [ ]:
dtEmployees.groupby('Gender')['YearsTenure'].describe()

        count      mean       std  min  25%  50%  75%  max
Gender
F        78.0  4.730769  2.322521  1.0  3.0  5.0  7.0  9.0
M        79.0  5.000000  2.531848  1.0  3.0  5.0  7.0  9.0

In [ ]:
dtEmployees.sample(n=3, random_state=10)

,EmployeeID,StoreID,Department,EmploymentType,Gender,HourlyRate,ContractedWeeklyHours,HireYear,YearsTenure
82,EMP0083,STR008,Customer Service,FullTime,M,18.58,40,2019,5
10,EMP0011,STR001,Stocking,FullTime,F,20.04,40,2019,5
130,EMP0131,STR013,Cashier,PartTime,M,18.69,28,2016,8

In [ ]:
dtPayroll.loc[dtPayroll['EmployeeID'] == 'EMP0001'].head(5)

    PayrollID EmployeeID StoreID  PayPeriod  ActualHoursWorked  GrossPayment
0  PAY0000001    EMP0001  STR001          1                 80       1385.60
1  PAY0000002    EMP0001  STR001          2                 78       1350.96
2  PAY0000003    EMP0001  STR001          3                 80       1385.60
3  PAY0000004    EMP0001  STR001          4                 80       1385.60
4  PAY0000005    EMP0001  STR001          5                 80       1385.60

In [ ]:
dtStoreActivity.groupby('StoreID').agg(
    avgSatisfaction=('CustomerSatisfactionScore','mean'),
    totalSales=('WeeklySales','sum')
).sort_values('avgSatisfaction', ascending=False).head(5)

         avgSatisfaction  totalSales
StoreID
STR011          4.108846   635931.01
STR013          4.075385  4483238.48
STR003          4.060577   748341.59
STR002          4.027308  2045012.62
STR004          4.022692  1871490.60

In [ ]:
dtEmployees.loc[dtEmployees['Department']=='Management','Gender'].value_counts()

Gender
M    9
F    7
Name: count, dtype: int64

In [ ]:
dtEmployees.groupby(['Department','HireYear'])['EmployeeID'].count().head(10)

Department        HireYear
Cashier           2015        6
                  2016        3
                  2017        8
                  2018        4
                  2019        8
                  2020        6
                  2021        9
                  2022        5
                  2023        6
Customer Service  2015        2
Name: EmployeeID, dtype: int64

In [ ]:
dtStores[['StoreID','OpenedYear','StoreSize']].sort_values('OpenedYear')

   StoreID  OpenedYear StoreSize
0   STR001        2011     Large
2   STR003        2011     Small
10  STR011        2011     Small
8   STR009        2011     Small
13  STR014        2013     Small
14  STR015        2014    Medium
5   STR006        2014     Small
6   STR007        2015    Medium
12  STR013        2016     Large
4   STR005        2016     Large
7   STR008        2018     Large
9   STR010        2018    Medium
3   STR004        2019    Medium
11  STR012        2020    Medium
1   STR002        2021    Medium

In [ ]:
dtStoreActivity.merge(dtStores[['StoreID','Region']], on='StoreID').groupby('Region')['TransactionCount'].sum()

Region
Alberta      258378
BC            99387
Maritimes    243713
Ontario      168680
Quebec        20658
Name: TransactionCount, dtype: int64

In [ ]:
print('Analysis complete.')

Analysis complete.